# ingress를 추가해서 이점
# 1. port가 사라짐
# 2. 라우팅(scale out)
# 3. CORS 안해도 됨(ingress가 인지한 것끼리 통신)

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sw-camp-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx  
  rules:
  - http:
      paths:
      - path: /()(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: vue002ser
            port: 
              number: 8000
      - path: /boot(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: boot002ser
            port: 
              number: 8001